#!/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
 
mkdir -p /var/log/logstash-forwarder
chown wh:wh /var/log/logstash-forwarder
exec setuidgid wh multilog t s10485760 n5 !tai64nlocal /var/log/logstash-forwarder

